package atm;

import java.io.Serializable;
import java.util.HashMap;

public class Language implements Serializable {
	private static final long serialVersionUID = 1L;
	private String language;
	HashMap<String,String> login;
	HashMap<String,String> admin;
	HashMap<String,String> user;
	String[] columnNames;
	
	public Language() {
		language = null;
		login = new HashMap<String, String>();
		admin = new HashMap<String, String>();
		user  = new HashMap<String, String>();
		columnNames = new String[Account.getAttributeNo()];
	}
	
	public String getLanguage() {
		return language;
	}
	
	/* 
	 * This is the default language of the system that will be displayed to the users.
	 */
	
	public void setEnglish() {
		language = "English";
		login.put("title","ATM");
		login.put("aboutMenu","About");
		login.put("settingMenu","Settings");
		login.put("languageMenu","Language");
		login.put("aboutATM","About ATM");
		login.put("aboutUs", "About Us");
		login.put("english","English");
		login.put("tagalog","Tagalog");
		login.put("accountNoLabel","Account No.:");
		login.put("passwordLabel","PIN:");
		login.put("loginButton","Login");
		login.put("exitQuestion","Do you want to exit?");
		login.put("exitTitle","Exit");
		login.put("nullMessage","You must fill all the required fields.");
		login.put("nullTitle","Null Input");
		login.put("loginMessage","Login Successful!");
		login.put("loginTitle","Login");
		login.put("invalidAccountMessage","Account does not exist.");
		login.put("invalidAccountTitle","Invalid Account");
		login.put("invalidPasswordMessage","Wrong Password! Please try again.");
		login.put("invalidPasswordTitle","Invalid Password");
		login.put("aboutATMMessage1","Automated Teller Machine\nAdmin: ");
		login.put("aboutATMMessage2","\n-Add/Remove/Update Accounts");
		login.put("aboutATMMessage3","\n-Import/Export/Append Accounts");
		login.put("aboutUsMessage","Created by:\nRajan Elio & James De Leon\nBSCSSE - N21\n");
		login.put("languageMessage","Changing the system language.\nPlease re-open the system.");
		login.put("languageTitle","Change Language");
		admin.put("title","Admin");
		admin.put("fileMenu","Files");
		admin.put("importAccount","Import Accounts");
		admin.put("exportAccount","Export Accounts");
		admin.put("appendAccount","Append Accounts");
		admin.put("addButton","Add Account");
		admin.put("removeButton","Remove Account");
		admin.put("updateButton","Update Account");
		admin.put("finishButton","Finish");
		admin.put("searchLabel","Search:");
		admin.put("exitQuestion",login.get("exitQuestion"));
		admin.put("exitTitle",login.get("exitTitle"));
		admin.put("accountNumber","Account Number:");
		admin.put("password","Password:");
		admin.put("accountName","Account Name:");
		admin.put("balance","Balance:");
		admin.put("saveButton","Save");
		admin.put("cancelButton","Cancel");
		admin.put("nullMessage",login.get("nullMessage"));
		admin.put("nullTitle",login.get("nullTitle"));
		admin.put("invalidAccountNoMessage","Account Number must not exceed 9 digits.");
		admin.put("invalidAccountNoTitle","Invalid Account Number");
		admin.put("addMessage","Account Added!");
		admin.put("invalidAccountMessage","Account Number must be unique.");
		admin.put("invalidAccountTitle","Invalid Account");
		admin.put("invalidBalanceMessage","Balance must be a positive number.");
		admin.put("invalidBalanceTitle","Invalid Balance");
		admin.put("updateQuestion","Do you want to update account: ");
		admin.put("updateMessage","Account Updated!");
		admin.put("removeQuestion","Do you want to remove selected account/s?");
		admin.put("removeMessage","Account/s Removed!");
		admin.put("saveQuestion","Do you want to save changes?");
		admin.put("saveMessage","Changes Saved!");
		admin.put("invalidFileMessage","File does not meet the required file format.");
		admin.put("invalidFileTitle","Invalid File");
		user.put("title","User");
		user.put("panelTitle","PLEASE CHOOSE SERVICES");
		user.put("withdrawButton","Cash Withdrawal");
		user.put("depositButton","Cash Deposit");
		user.put("transferButton","Transfer Funds");
		user.put("balanceInquiryButton","Balance Inquiry");
		user.put("settingButton","Account Settings");
		user.put("logoutButton","Logout");
		user.put("backButton","Back");
		user.put("withdrawToolTip","Withdraw an amount from the account");
		user.put("depositToolTip","Deposit an amount to the account");
		user.put("transferToolTip","Transfer an amount to another account");
		user.put("balanceInquiryToolTip","Check the account balance");
		user.put("settingToolTip","Change the PIN or password of the account");
		user.put("logoutToolTip","Logout of the current account");
		user.put("exitQuestion",login.get("exitQuestion"));
		user.put("exitTitle",login.get("exitTitle"));
		user.put("withdrawTitle","CASH WITHDRAWAL");
		user.put("amount","Amount:");
		user.put("withdraw","Withdraw");
		user.put("nullMessage",login.get("nullMessage"));
		user.put("nullTitle",login.get("nullTitle"));
		user.put("invalidAmountMessage","Amount must be a positive number.");
		user.put("invalidAmountTitle","Invalid Amount");
		user.put("restrictAmountMessage","Amount must be divisible by 100.");
		user.put("withdrawQuestion","Are you sure you want to withdraw?");
		user.put("withdrawMessage","Withdraw Successful!");
		user.put("invalidAccountMessage","Account does not exist.");
		user.put("invalidAccountTitle","Invalid Account");
		user.put("invalidBalanceMessage","Insufficient Funds.");
		user.put("invalidBalanceTitle","Invalid Balance");
		user.put("depositTitle","CASH DEPOSIT");
		user.put("deposit","Deposit");
		user.put("depositQuestion","Are you sure you want to deposit?");
		user.put("depositMessage","Deposit Successful!");
		user.put("transferTitle","TRANSFER FUNDS");
		user.put("transferLabel","Transferee Account:");
		user.put("amountLabel","Amount to Transfer:");
		user.put("transfer","Transfer");
		user.put("invalidTransfereeMessage","Transferee Account must not be the current account.");
		user.put("invalidTransfereeTitle","Invalid Transferee Account");
		user.put("transferQuestion","Are you sure you want to transfer?");
		user.put("transferMessage","Transfer Successful!");
		user.put("balanceInquiryTitle","BALANCE INQUIRY");
		user.put("accNoLabel","Account Number:");
		user.put("accNameLabel","Account Holder:");
		user.put("balanceLabel","Account Balance:");
		user.put("settingTitle","ACCOUNT SETTINGS");
		user.put("oldLabel","OLD PIN:");
		user.put("newLabel","NEW PIN:");
		user.put("confirmLabel","CONFIRM NEW PIN:");
		user.put("change","Change");
		user.put("invalidPINMessage","New PIN and Confirm PIN does not match.");
		user.put("invalidPINTitle","Mismatch PIN Input");
		user.put("samePINMessage","Old PIN and New PIN are the same.");
		user.put("samePINTitle","Same PIN Input");
		user.put("settingQuestion","Are you sure you want to change PIN?");
		user.put("setting","Change PIN");
		user.put("settingMessage","Change PIN Successful!");
		user.put("invalidPasswordMessage","Incorrect Current PIN.");
		user.put("invalidPasswordTitle","Invalid Current PIN");
		user.put("logoutQuestion","Do you want to logout?");
		String[] columnNames = {"Account Number","Password","Name","Balance"};
		this.columnNames = columnNames;
	}
	
	/* 
	 * In this part, all the English terms are translated into Filipino in which the user can freely choose 
	 * on what language will be displayed to them.
	 */
	
	public void setTagalog() {
		language = "Tagalog";
		login.put("title","ATM");
		login.put("aboutMenu","Tungkol");
		login.put("settingMenu","Settings");
		login.put("languageMenu","Wika");
		login.put("aboutATM","Tungkol sa ATM");
		login.put("aboutUs", "Tungkol sa mga gumawa");
		login.put("english","Ingles");
		login.put("tagalog","Tagalog");
		login.put("accountNoLabel","Account No.:");
		login.put("passwordLabel","PIN:");
		login.put("loginButton","Mag log-in");
		login.put("exitQuestion","Gusto mo bang umalis?");
		login.put("exitTitle","Umalis");
		login.put("nullMessage","Kailangan punuin ang mga susulatan.");
		login.put("nullTitle","Walang nilagay");
		login.put("loginMessage","Matagumpay ang pag log-in!");
		login.put("loginTitle","Mag log-in");
		login.put("invalidAccountMessage","Walang katugmang account");
		login.put("invalidAccountTitle","Hindi tama ang Account");
		login.put("invalidPasswordMessage","Mali ang password. Ulitin.");
		login.put("invalidPasswordTitle","Hindi tama ang password.");
		login.put("aboutATMMessage1","Automated Teller Machine\nTagapangasiwa: ");
		login.put("aboutATMMessage2","\n-Magdagdag/Magtanggal/Mag-update ng mga Account ");
		login.put("aboutATMMessage3","\n-Magpasok/Magluwas/Magdugtong ng mga Account ");
		login.put("aboutUsMessage","Ginawa nina: \nRajan Elio at James De Leon\nBSCSSE - N21 \n");
		login.put("languageMessage","Papalitan ang Wika. \nBuksan muli ang system.");
		login.put("languageTitle","Palitan ang Wika");
		admin.put("title","Tagapangasiwa");
		admin.put("fileMenu","Files");
		admin.put("importAccount","Magpasok ng mga Account");
		admin.put("exportAccount","Magluwas ng mga Account");
		admin.put("appendAccount","Magdugtong ng mga Account");
		admin.put("addButton","Magdagdag ng Account");
		admin.put("removeButton","Magtanggal ng Account");
		admin.put("updateButton","I-update ang Account");
		admin.put("finishButton","Tapusin");
		admin.put("searchLabel","Hanap:");
		admin.put("exitQuestion",login.get("exitQuestion"));
		admin.put("exitTitle",login.get("exitTitle"));
		admin.put("accountNumber","Numero ng Account:");
		admin.put("password","Password:");
		admin.put("accountName","Pangalan ng Account:");
		admin.put("balance","Balanse:");
		admin.put("saveButton","I-save");
		admin.put("cancelButton","Kanselahin");
		admin.put("nullMessage",login.get("nullMessage"));
		admin.put("nullTitle",login.get("nullTitle"));
		admin.put("invalidAccountNoMessage","Hindi maaring lumagpas sa 9 ang bilang ng Account Number.");
		admin.put("invalidAccountNoTitle","Mali ang Numero ng Account");
		admin.put("addMessage","Naidagdag ang Account!");
		admin.put("invalidAccountMessage","Hindi maari gumawa ng may kaparehong Numero ng Account");
		admin.put("invalidAccountTitle","Hindi tama ang Account");
		admin.put("invalidBalanceMessage","May laman dapat ang iyong account");
		admin.put("invalidBalanceTitle","Hindi tama ang Balanse");
		admin.put("updateQuestion","Gusto mo bang i-update ang account: ");
		admin.put("updateMessage","Na-update na ang account!");
		admin.put("removeQuestion","Gusto mo bang tanggalin ang mga napiling account?");
		admin.put("removeMessage","Natanggal na ang mga account!");
		admin.put("saveQuestion","Gusto mo bang mai-save ang mga binago?");
		admin.put("saveMessage","Na i-save na ang mga binago!");
		admin.put("invalidFileMessage","Hindi nakamit ng File ang kailangang format.");
		admin.put("invalidFileTitle","Hindi tama ang File");
		user.put("title","Gumagamit");
		user.put("panelTitle","PUMILI NG MGA SERBISYO");
		user.put("withdrawButton","Maglabas ng Salapi");
		user.put("depositButton","Magdeposito ng Salapi");
		user.put("transferButton","Maglipat ng Salapi");
		user.put("balanceInquiryButton","Tignan ang Balanse");
		user.put("settingButton","Account Settings");
		user.put("logoutButton","Mag logout");
		user.put("backButton","Bumalik");
		user.put("withdrawToolTip","Maglabas ng salapi mula sa account");
		user.put("depositToolTip","Mag deposito ng salapi sa account");
		user.put("transferToolTip","Maglipat ng salapi sa ibang account");
		user.put("balanceInquiryToolTip","Tignan ang balanse ng account");
		user.put("settingToolTip","Baguhin ang PIN o password ng account");
		user.put("logoutToolTip","Mag logout mula sa account");
		user.put("exitQuestion",login.get("exitQuestion"));
		user.put("exitTitle",login.get("exitTitle"));
		user.put("withdrawTitle","PAGLALABAS NG SALAPI");
		user.put("amount","Halaga:");
		user.put("withdraw","Maglabas");
		user.put("nullMessage",login.get("nullMessage"));
		user.put("nullTitle",login.get("nullTitle"));
		user.put("invalidAmountMessage","Ang halaga ay dapat mas malaki sa 0.");
		user.put("invalidAmountTitle","Hindi tama ang halaga");
		user.put("restrictAmountMessage","Ang halaga ay dapat nahahati sa 100.");
		user.put("withdrawQuestion","Sigurado ka bang gusto mo maglabas ng salapi?");
		user.put("withdrawMessage","Matagumpay na ang paglabas ng salapi!");
		user.put("invalidAccountMessage","Walang katugmang account");
		user.put("invalidAccountTitle","Hindi tama ang Account");
		user.put("invalidBalanceMessage","Hindi sapat ang salapi");
		user.put("invalidBalanceTitle","Hindi tama ang salapi");
		user.put("depositTitle","PAG-DEPOSITO");
		user.put("deposit","I-deposito");
		user.put("depositQuestion","Sigurado ka bang gusto mo mag deposito ng salapi?");
		user.put("depositMessage","Matagumpay ang pag dedeposito!");
		user.put("transferTitle","PAGLIPAT NG SALAPI");
		user.put("transferLabel","Account na Paglilipatan:");
		user.put("amountLabel","Halaga ng Ililipat:");
		user.put("transfer","I-lipat");
		user.put("invalidTransfereeMessage","Ang paglilipatan na account ay hindi dapat ang gamit na account.");
		user.put("invalidTransfereeTitle","Hindi tama ang paglilipatan na account");
		user.put("transferQuestion","Sigurado ka bang gusto mo ilipat ang salapi?");
		user.put("transferMessage","Matagumpay ang paglipat!");
		user.put("balanceInquiryTitle","BALANSE");
		user.put("accNoLabel","Numero ng Account:");
		user.put("accNameLabel","May ari ng Account:");
		user.put("balanceLabel","Balanse ng Account:");
		user.put("settingTitle","ACCOUNT SETTINGS");
		user.put("oldLabel","LUMANG PIN:");
		user.put("newLabel","BAGONG PIN:");
		user.put("confirmLabel","KUMPIRMANG BAGONG PIN:");
		user.put("change","Baguhin");
		user.put("invalidPINMessage","Hindi tugma ang bagong Pin at kumpimang bagong PIN.");
		user.put("invalidPINTitle","Hindi tugma ang PIN");
		user.put("samePINMessage","Ang lumang PIN ay kapareho ng bagong PIN.");
		user.put("samePINTitle","Parehas ang PIN");
		user.put("settingQuestion","Sigurado ka bang gusto mong baguhin ang iyong PIN?");
		user.put("setting","Pagpalit ng PIN");
		user.put("settingMessage","Matagumpay ang Pagpapalit ng PIN!");
		user.put("invalidPasswordMessage","Mali ang kasalukuyang PIN.");
		user.put("invalidPasswordTitle","Mali ang PIN");
		user.put("logoutQuestion","Gusto mo bang mag logout?");
		String[] columnNames = {"Numero ng Account","Password","Pangalan ng Account","Balanse"};
		this.columnNames = columnNames;
	}
}
